<?php
define('COLL_FILE_BASE_SCHEMA', 'public://digicoll');

require_once 'collarchive.page.inc';
require_once 'collarchive.crud.inc';

function collarchive_menu() {
  $items['search'] =
    array(
      'title' => 'collection',
      'description' => 'collection.',
      'page callback' => '_collarchive_page',
      'access arguments' => array('view collection'),
    );
  $items['admin/config/coll/archive_crud'] =
    array(
      'title' => 'Collection Archive Crud',
      'description' => '',
      'page callback' => '_collarchive_crud_page',
      'access arguments' => array('admin collection'),
      'weight' => -5,
    );
  $items['admin/config/coll/settings'] =
    array(
      'title' => 'Collection Settings',
      'description' => '',
      'page callback' => '_collarchive_misc_settings',
      'access arguments' => array('admin collection'),
      'weight' => -5,
    );
  return $items;
}

function collarchive_node_view($node, $view_mode, $langcode) {
  if($node->type != 'collection') return;
  $identifier = (int)$node->field_identifier['und'][0]['value'];
  $qs = DT::array_get($_GET, 'qs', '');
  if(!$qs) $qs = DT::array_get($_GET, 'in', '');
  $row = DT::array_get($_GET, 'row', 0);
  $func = '_coll_node_view_'.$view_mode;
  if(is_callable($func)) {
    $func($node, $qs, $row, $identifier);
  }
}
